#!/usr/bin/env php
<?php
/**
 * Build index.min.php from index.php (CSS/JS/HTML/PHP comment minification).
 *
 * Usage (from repo root):
 *   php scripts/build-min.php
 *   php scripts/build-min.php --check   # exit 1 if index.min.php is stale
 */

declare(strict_types=1);

$repoRoot = dirname(__DIR__);
$sourcePath = $repoRoot . '/index.php';
$outputPath = $repoRoot . '/index.min.php';
$checkOnly = in_array('--check', $argv ?? [], true);

if (!is_readable($sourcePath)) {
    fwrite(STDERR, "Source not found: {$sourcePath}\n");
    exit(1);
}

function minifyCss(string $css): string
{
    $css = preg_replace('!/\*.*?\*/!s', '', $css) ?? $css;
    $css = preg_replace('/\s+/', ' ', $css) ?? $css;
    $css = preg_replace('/\s*([{}:;,>+~])\s*/', '$1', $css) ?? $css;
    return trim($css);
}

function minifyJs(string $js): string
{
    $js = preg_replace('#/\*[\s\S]*?\*/#', '', $js) ?? $js;
    $js = preg_replace('#^\s*//.*$#m', '', $js) ?? $js;
    $js = preg_replace('/\s+/', ' ', $js) ?? $js;
    $js = preg_replace('/\s*([{}();,:=\[\]?&|+\-*\/<>!])\s*/', '$1', $js) ?? $js;
    return trim($js);
}

function minifyHtmlBlock(string $html): string
{
    $protected = [];
    $i = 0;
    $html = preg_replace_callback(
        '#<(pre|textarea|script|style)(\s[^>]*)?>.*?</\1>#si',
        static function (array $m) use (&$protected, &$i): string {
            $key = '___PROTECTED_' . ($i++) . '___';
            $protected[$key] = $m[0];
            return $key;
        },
        $html
    ) ?? $html;

    $html = preg_replace('/\s+/', ' ', $html) ?? $html;
    $html = preg_replace('/>\s+</', '><', $html) ?? $html;

    return strtr($html, $protected);
}

function minifyStyleScriptBlocks(string $chunk): string
{
    $chunk = preg_replace_callback(
        '#<style(\s[^>]*)?>(.*?)</style>#si',
        static function (array $m): string {
            return '<style' . $m[1] . '>' . minifyCss($m[2]) . '</style>';
        },
        $chunk
    ) ?? $chunk;

    return preg_replace_callback(
        '#<script(?![^>]*\bsrc=)([^>]*)>(.*?)</script>#si',
        static function (array $m): string {
            return '<script' . $m[1] . '>' . minifyJs($m[2]) . '</script>';
        },
        $chunk
    ) ?? $chunk;
}

function minifyInlinePhpBlock(string $code, string $openTag): string
{
    $min = minifyPhpCode($code);
    // PHP only recognizes inline blocks when <?php is followed by whitespace.
    if ($openTag === '<?php' && $min !== '') {
        $min = ' ' . ltrim($min);
    }

    return $min;
}

function minifyPhpCode(string $code): string
{
    // token_get_all() only parses PHP when the snippet starts with an open tag.
    $tokens = token_get_all("<?php\n" . $code);
    $out = '';
    $n = count($tokens);

    for ($i = 0; $i < $n; $i++) {
        if ($i === 0 && is_array($tokens[$i]) && $tokens[$i][0] === T_OPEN_TAG) {
            continue;
        }
        if ($i === 1 && is_array($tokens[$i]) && $tokens[$i][0] === T_WHITESPACE && trim($tokens[$i][1]) === '') {
            continue;
        }
        $token = $tokens[$i];

        if (is_array($token) && $token[0] === T_VARIABLE && $token[1] === '$css') {
            $j = $i + 1;
            while ($j < $n && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) {
                $j++;
            }
            if ($j < $n && is_string($tokens[$j]) && $tokens[$j] === '=') {
                $j++;
                while ($j < $n && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) {
                    $j++;
                }
                if ($j < $n && is_array($tokens[$j]) && $tokens[$j][0] === T_CONSTANT_ENCAPSED_STRING && $tokens[$j][1][0] === "'") {
                    $raw = substr($tokens[$j][1], 1, -1);
                    $raw = preg_replace("/\\\\(['\\\\])/", '$1', $raw) ?? $raw;
                    $min = minifyCss($raw);
                    $min = str_replace(['\\', "'"], ['\\\\', "\\'"], $min);
                    $out .= '$css=\'' . $min . '\'';
                    $i = $j;
                    continue;
                }
            }
        }

        if (is_string($token)) {
            $out .= $token;
            continue;
        }

        if ($token[0] === T_COMMENT || $token[0] === T_DOC_COMMENT) {
            continue;
        }

        if ($token[0] === T_WHITESPACE) {
            if ($out !== '' && !preg_match('/[\s({\[;,=:$]$/', $out)) {
                $out .= ' ';
            }
            continue;
        }

        $out .= $token[1];
    }

    return $out;
}

function buildMinifiedPhp(string $source): string
{
    $banner = "<?php /* Generated by scripts/build-min.php — edit index.php and rebuild. */ ";
    $pos = 0;
    $len = strlen($source);
    $out = '';

    if (strncmp($source, '<?php', 5) !== 0) {
        fwrite(STDERR, "Expected index.php to start with <?php\n");
        exit(1);
    }

    // Drop the source file banner comment block; build script adds its own.
    $pos = 5;
    if (preg_match('/^\s*\/\*\*.*?\*\//s', substr($source, 5), $m)) {
        $pos = 5 + strlen($m[0]);
    }

    $inPhp = true;
    $isMainPhpBlock = true;
    $lastOpenTag = '<?php';

    while ($pos < $len) {
        if ($inPhp) {
            $close = strpos($source, '?>', $pos);
            if ($close === false) {
                $code = substr($source, $pos);
                $out .= $isMainPhpBlock ? minifyPhpCode($code) : minifyInlinePhpBlock($code, $lastOpenTag);
                break;
            }
            $code = substr($source, $pos, $close - $pos);
            $out .= $isMainPhpBlock
                ? minifyPhpCode($code)
                : minifyInlinePhpBlock($code, $lastOpenTag);
            $isMainPhpBlock = false;
            $out .= '?>';
            $pos = $close + 2;
            $inPhp = false;
            continue;
        }

        if (preg_match('/<\?(?:php|=)/', $source, $m, PREG_OFFSET_CAPTURE, $pos)) {
            $open = $m[0][1];
            $html = substr($source, $pos, $open - $pos);
            $html = minifyStyleScriptBlocks($html);
            $html = minifyHtmlBlock($html);
            $out .= $html;
            $out .= $m[0][0];
            $lastOpenTag = $m[0][0];
            $pos = $open + strlen($m[0][0]);
            $inPhp = true;
            continue;
        }

        $html = substr($source, $pos);
        $html = minifyStyleScriptBlocks($html);
        $out .= minifyHtmlBlock($html);
        break;
    }

    return $banner . ltrim($out);
}

$source = file_get_contents($sourcePath);
if ($source === false) {
    fwrite(STDERR, "Failed to read {$sourcePath}\n");
    exit(1);
}

$built = buildMinifiedPhp($source);

if ($checkOnly) {
    if (!is_readable($outputPath)) {
        fwrite(STDERR, "index.min.php is missing; run: php scripts/build-min.php\n");
        exit(1);
    }
    $existing = file_get_contents($outputPath);
    if ($existing !== $built) {
        fwrite(STDERR, "index.min.php is out of date; run: php scripts/build-min.php\n");
        exit(1);
    }
    fwrite(STDOUT, "index.min.php is up to date.\n");
    exit(0);
}

if (file_put_contents($outputPath, $built) === false) {
    fwrite(STDERR, "Failed to write {$outputPath}\n");
    exit(1);
}

$sourceBytes = strlen($source);
$outputBytes = strlen($built);
$sourceGz = strlen(gzencode($source, 9));
$outputGz = strlen(gzencode($built, 9));

fwrite(STDOUT, "Wrote {$outputPath}\n");
fwrite(STDOUT, sprintf(
    "Size: %s → %s bytes (%.1f%%), gzip: %s → %s bytes (%.1f%%)\n",
    number_format($sourceBytes),
    number_format($outputBytes),
    100 - ($outputBytes / max(1, $sourceBytes) * 100),
    number_format($sourceGz),
    number_format($outputGz),
    100 - ($outputGz / max(1, $sourceGz) * 100)
));

$lint = shell_exec('php -l ' . escapeshellarg($outputPath) . ' 2>&1');
if ($lint === null || strpos($lint, 'No syntax errors') === false) {
    fwrite(STDERR, "Syntax check failed:\n{$lint}\n");
    exit(1);
}

foreach (['<?phpif', '<?phpelse', '<?phpendif', '<?phpforeach', '<?phpendforeach'] as $brokenTag) {
    if (strpos($built, $brokenTag) !== false) {
        fwrite(STDERR, "Build produced invalid inline PHP ({$brokenTag}); fix scripts/build-min.php.\n");
        exit(1);
    }
}

fwrite(STDOUT, trim($lint) . "\n");
